### ISSUE TITLE
Audio processing no such file or directory

### ISSUE THREAD

**Issue by nmb-paperspace** [gradient-ai/Graphcore-HuggingFace#54]
`audio_classification.ipynb` cell beginning with `encoded_dataset = dataset.map(` fails after some time with

```
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/huggingface_caches/datasets/downloads/extracted/db12ee2fddf4d149ad4933a337eb0b88a31fe9cd5546942e648269430d799957/four/d7a58714_nohash_0.wav'
```

This blocks the `trainer = IPUTrainer(` cell because `encoded_dataset` is not defined.

**Comment by rahult-graphcore** [comment]
I just ran this on Paperspace but could not reproduce the error. I wonder if you had run it before the datasets had finished symlinking?

**Comment by nmb-paperspace** [comment]
Hm, that's curious. I just retried it by doing (HF runtime, IPU-16 machine with 12h shutdown, rest defaults):
- Wait for the log on startup to display setup done: `2023-01-16T17:22:18.902781163Z stdout F Finished running setup.sh.`
- Also it appears to show all datasets as mounted data sources in the GUI
- Step the cells up to HF login and add HF write access token
- Run all remaining cells to end
The cell with `encoded_dataset = dataset.map(preprocess_function, remove_columns=["audio", "file"], batched=True, num_proc=64)` fails with the same error. Here's the full traceback:
```
---------------------------------------------------------------------------
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/multiprocess/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.8/dist-packages/datasets/arrow_dataset.py", line 562, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/datasets/arrow_dataset.py", line 529, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/datasets/fingerprint.py", line 480, in wrapper
    out = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/datasets/arrow_dataset.py", line 3247, in _map_single
    batch = apply_function_on_filtered_inputs(
  File "/usr/local/lib/python3.8/dist-packages/datasets/arrow_dataset.py", line 3123, in apply_function_on_filtered_inputs
    processed_inputs = function(*fn_args, *additional_args, **fn_kwargs)
  File "<ipython-input-17-6c1f750b179e>", line 3, in preprocess_function
    audio_arrays = [x["array"] for x in examples["audio"]]
  File "/usr/local/lib/python3.8/dist-packages/datasets/formatting/formatting.py", line 282, in __getitem__
    value = self.format(key)
  File "/usr/local/lib/python3.8/dist-packages/datasets/formatting/formatting.py", line 385, in format
    return self.formatter.format_column(self.pa_table.select([key]))
  File "/usr/local/lib/python3.8/dist-packages/datasets/formatting/formatting.py", line 447, in format_column
    column = self.python_features_decoder.decode_column(column, pa_table.column_names[0])
  File "/usr/local/lib/python3.8/dist-packages/datasets/formatting/formatting.py", line 228, in decode_column
    return self.features.decode_column(column, column_name) if self.features else column
  File "/usr/local/lib/python3.8/dist-packages/datasets/features/features.py", line 1857, in decode_column
    [decode_nested_example(self[column_name], value) if value is not None else None for value in column]
  File "/usr/local/lib/python3.8/dist-packages/datasets/features/features.py", line 1857, in <listcomp>
    [decode_nested_example(self[column_name], value) if value is not None else None for value in column]
  File "/usr/local/lib/python3.8/dist-packages/datasets/features/features.py", line 1298, in decode_nested_example
    return schema.decode_example(obj, token_per_repo_id=token_per_repo_id)
  File "/usr/local/lib/python3.8/dist-packages/datasets/features/audio.py", line 166, in decode_example
    array, sampling_rate = self._decode_non_mp3_path_like(path, token_per_repo_id=token_per_repo_id)
  File "/usr/local/lib/python3.8/dist-packages/datasets/features/audio.py", line 270, in _decode_non_mp3_path_like
    with xopen(path, "rb", use_auth_token=use_auth_token) as f:
  File "/usr/local/lib/python3.8/dist-packages/datasets/download/streaming_download_manager.py", line 445, in xopen
    return open(main_hop, mode, *args, **kwargs)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/huggingface_caches/datasets/downloads/extracted/db12ee2fddf4d149ad4933a337eb0b88a31fe9cd5546942e648269430d799957/four/d7a58714_nohash_0.wav'
"""

The above exception was the direct cause of the following exception:

FileNotFoundError                         Traceback (most recent call last)
<ipython-input-19-ec93aee72447> in <module>
----> 1 encoded_dataset = dataset.map(preprocess_function, remove_columns=["audio", "file"], batched=True, num_proc=64)
      2 encoded_dataset

/usr/local/lib/python3.8/dist-packages/datasets/dataset_dict.py in map(self, function, with_indices, with_rank, input_columns, batched, batch_size, drop_last_batch, remove_columns, keep_in_memory, load_from_cache_file, cache_file_names, writer_batch_size, features, disable_nullable, fn_kwargs, num_proc, desc)
    814             cache_file_names = {k: None for k in self}
    815         return DatasetDict(
--> 816             {
    817                 k: dataset.map(
    818                     function=function,

/usr/local/lib/python3.8/dist-packages/datasets/dataset_dict.py in <dictcomp>(.0)
    815         return DatasetDict(
    816             {
--> 817                 k: dataset.map(
    818                     function=function,
    819                     with_indices=with_indices,

/usr/local/lib/python3.8/dist-packages/datasets/arrow_dataset.py in map(self, function, with_indices, with_rank, input_columns, batched, batch_size, drop_last_batch, remove_columns, keep_in_memory, load_from_cache_file, cache_file_name, writer_batch_size, features, disable_nullable, fn_kwargs, num_proc, suffix_template, new_fingerprint, desc)
   2937 
   2938                     for index, async_result in results.items():
-> 2939                         transformed_shards[index] = async_result.get()
   2940 
   2941             assert (

/usr/local/lib/python3.8/dist-packages/multiprocess/pool.py in get(self, timeout)
    769             return self._value
    770         else:
--> 771             raise self._value
    772 
    773     def _set(self, i, obj):

FileNotFoundError: [Errno 2] No such file or directory: '/tmp/huggingface_caches/datasets/downloads/extracted/db12ee2fddf4d149ad4933a337eb0b88a31fe9cd5546942e648269430d799957/four/d7a58714_nohash_0.wav'
```
The last numbered item shown is 60
![Screen Shot 2023-01-16 at 10 14 09 AM](https://user-images.githubusercontent.com/74800360/212743456-2756b757-a5cb-43b7-8fac-2d844ab14994.png)

If the above is pointing to a missing symlink I would need to list the contents of `/datasets` to check they are as expected before running the notebook. What's the expected subdirectory content for this one?

**Comment by rahult-graphcore** [comment]
I can reproduce this now, will investigate.

**Comment by nmb-paperspace** [comment]
Yes, OK to close
